### ISSUE TITLE
屋外での超音波センサーの挙動を改善したい

### ISSUE THREAD

**Issue by Dodai-Dodai** [Dodai-Dodai/skramm_BLEBeacon#5]
屋外かつ計測距離が長距離である場所では風の影響で反応しなかったりしてしまうので、その辺をハード(センサーも含めて)・ソフト両面から改善したい

**Comment by Cinnamoroll-910** [comment]
バスの排気ガスの成分から、一酸化炭素、二酸化窒素が多い。つまり、バスが一定値の距離に達した時、かつ一酸化炭素、二酸化窒素が検出できた時にBeaconを発することができたら、風などの影響を受けないのではないか。と考えました。

**Comment by Dodai-Dodai** [comment]
車通りが少ない所なら有効な気がしますが、枚方市駅周辺のバス停はどこも渋滞多発地点なのでバスが来たとしても濃度がそんなに変わらない可能性があります。一酸化炭素や二酸化炭素の濃度がいい感じに変化するというデータが取れれば可能性はあると思います。

**Comment by muta1725** [comment]
排気ガス自体も風の影響を受けやすいと思うので精度として微妙な気がします。上でも言われているように、バスの発着に合わせて濃度が変化するデータが取れれば可能性ありだと思います。

**Comment by Dodai-Dodai** [comment]
開発終了につきクローズ
